/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package littlescheduler.app;

import littlescheduler.view.MainFrame;

public class App {
    public static void main(String[] args) {
        new MainFrame();
    }
}
