/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package littlescheduler.app;

public class App {
    public static void main(String[] args) {
        new Schedule_Frame();
    }
}
